name: 'ClusterFuzz'
description: 'GitHub Action that uploads fuzz artifacts to your ClusterFuzz installation.'
author: '@marcus-jump'
inputs:
  bucket-name:
    description: 'Name of the receiving bucket'
    required: true
  object-prefix:
    description: 'Fuzz targets destination: should look like "gs://<bucket>/<objectpath>"". Action will drop artifacts at "gs://<bucket>/<object-prefix>.<datetime>.zip"'
    required: true
  project-id:
    description: 'Google Cloud Project ID'
    required: true
  service-account-credentials:
    description: 'Credentials for the service account that is allowed to interact with the Fuzz artifact bucket (in JSON)'
  artifact-dir:
    description: 'Path to directory containing fuzz targets.'
    required: true
  qualifier:
    description: Qualifier to add to the output target name
    required: false
runs:
  using: 'node16'
  main: 'dist/index.js'